### PR TITLE
update text-unidecode 1.13

### PR DESCRIPTION
**Pull request by sodre**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sodre** [comment]
@conda-forge-admin, please rerender

**Comment by sodre** [comment]
@conda-forge/text-unidecode, an update to this recipe is ready for review/merge.

**Comment by ocefpaf** [comment]
@sodre sorry, I missed this one. Do you need this version? If so can you rebase it and I'll merge it in a branch for you.

**Comment by bollwyvl** [comment]
Looks like python-slugify needs this (or newer)...
```
python-slugify 4.0.0 has requirement text-unidecode>=1.3, but you have text-unidecode 1.2.
```
Will submit new PR...

**Comment by bollwyvl** [comment]
Ah, bad pin there:
https://github.com/conda-forge/python-slugify-feedstock/pull/22

Suppose this can be closed!

**Comment by ocefpaf** [comment]
Closing this as stale. We can reopen it if this is still needed.

**Pull request closed without merging**
